version: "3.8"

services:
  nuxt-app:
    build: .
    container_name: nuxt-app
    networks:
      - web
    restart: always
    ports:
      - "80:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  web:
    driver: bridge
